### ISSUE TITLE
Not compatible with Firefox 45.0.1

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Rudloff/emoji-everywhere#1]
This addon have no effect when I installed into Firefox 45.0.1.

**Comment by joedf** [comment]
Seems to work just fine.
You have to manually download the plugin file and open it in firefox to have it installed correctly.
You may then test with this webpage: http://www.emojicode.org/

**Comment by Rudloff** [comment]
It works for me on Firefox 46.0a2.
If you can still reproduce, could you provide some logs (from the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console))?

**Comment by KrasnayaPloshchad** [comment]
Oh, I forgot I installed this addon when I using private mode directly via right click the icon on the task bar.

![1](http://i.imgur.com/XduG4Km.png)

**Comment by Rudloff** [comment]
By default, addons are disabled in private browsing (unless they request the [`private-browsing`](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing#Opting_into_private_browsing) permission).
I am not sure I want to add this permission to Emoji Everywhere because:
- It calls a CDN on every page.
- It does not provide an essential feature.

**Comment by joedf** [comment]
Established as not a bug. Close issue?
